config/routes.rb
Rails.application.routes.draw do

  root 'resumes#index'
  resources :resumes, except: [:new, :update] do
    resources :objectives, only: [:create, :update, :edit, :show]
    resources :skills, except: [:index, :show]
    resources :schools, except: [:index, :show]
    resources :experiences, except: [:index, :show] do
      resources :projects, except: [:index, :show]
    end
    resources :hobbies, except: [:index, :show]
    resources :references, except: [:index, :show]
    resources :customs, except: [:index, :show]
    resources :snippets, except: [:index, :show]
  end

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :edit, :update] do
    resources :gravatars, only: [:create, :edit, :update]
  end

end

app/models/gravatar.rb
class Gravatar < ActiveRecord::Base
  belongs_to :user
end

app/controllers/gravatars_controller.rb
class GravatarsController < ApplicationController
  before_action :set_gravatar
  before_action :set_user

  def edit

  end

  def update
    if @gravatar.update(params.require(:gravatar).permit(:show_image, :use_custom_url, :custom_image_url))
      flash[:notice] = "Gravatar settings updated"
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_gravatar
    @gravatar = Gravatar.find(params[:id])
  end

  def set_user
    @user = User.find_by(slug: params[:user_id])
  end
end

app/views/gravatars/_form.html.erb
<%= render 'shared/errors', obj: @gravatar %>
<%= form_for [@user, @gravatar] do |f| %>
  <fieldset>
    <legend><%= create_or_update(@gravatar) %></legend>
      <%= f.check_box :show_image  %>
      <%= f.label :show_imge %>
      <%= f.check_box :use_custom_url %>
      <%= f.label :use_custom_url %>
      <br />
      <%= f.label :custom_image_url %>
      <%= f.text_field :custom_image_url %>
    <%= f.submit create_or_update(@gravatar), class: 'button small radius' %>
  </fieldset>
<% end %>

app/views/gravatars/_gravatar.html.erb
<% grav_class = ((current_page? resumes_path) || (current_page? root_path)) ? 'gravatar index left' : 'gravatar left' %>
<% if res_obj.user.gravatar.show_image %>
  <% if res_obj.user.gravatar.use_custom_url %>
    <%= image_tag res_obj.user.gravatar.custom_image_url, class: grav_class %>
  <% else %>
    <%= image_tag res_obj.user.gravatar_url(size: '150'), class: grav_class %>
  <% end %>
<% end %>

app/views/gravatars/edit.html.erb
<%= render 'shared/title', title: "Profile Image" %>
<div class="row">
  <div class="medium-2 columns">
    <%= render @user.gravatar, res_obj: @user.resume %>
  </div>
  <div class="medium-10 columns">
    <p style="margin-top: 1rem;">You can choose whether to use your gravatar based on your email address.  Find out how to get your gravatar at <%= link_to "gravatar.com", 'http://gravatar.com' %>.  You can also choose not to display an image on your resume or enter a custom url for your image.</p>
  </div>
</div>
<%= render 'form' %>
<%= link_to "<i class=\"fi-arrow-left\"></i> Back".html_safe, edit_resume_path(@user.resume), title: "Back to Dashboard" %>