config/routes.rb
Rails.application.routes.draw do

  root 'resumes#index'
  resources :resumes, except: [:new, :update] do
    resources :objectives, only: [:create, :update, :edit, :show]
    resources :skills, except: [:index, :show]
    resources :schools, except: [:index, :show]
    resources :experiences, except: [:index, :show] do
      resources :projects, except: [:index, :show]
    end
    resources :hobbies, except: [:index, :show]
    resources :references, except: [:index, :show]
    resources :customs, except: [:index, :show]
    resources :snippets, except: [:index, :show]
  end

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :edit, :update] do
    resources :gravatars, only: [:create, :edit, :update]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  sluggable_column :last_name

  include Gravtastic
  gravtastic

  has_one :resume
  has_one :gravatar
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3 }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :set_resume, only: [:edit, :update]
  before_action :require_user, except: [:new, :create]

  def new
    @user = User.new
    @resume = Resume.new
  end

  def create
    @user = User.new(user_params)
    @resume = Resume.new
    @gravatar = Gravatar.new

    if @user.save
      flash[:notice] = "You are registered"

      #associate resume
      @resume.user = @user
      @resume.save

      #associate gravatar
      @gravatar.user = @user
      @gravatar.use_custom_url = false
      @gravatar.show_image = true
      @gravatar.save

      session[:user_id] = @user.id
      session[:resume_id] = @resume.id
      redirect_to edit_resume_path(@resume)
    else
      render :new
    end
  end

  def edit
    if current_user.id != @user.id
      flash[:notice]
      redirect_to edit_user_path(current_user)
    end
  end

  def update
    if current_user.id != @user.id
      flash[:notice]
      redirect_to edit_user_path(current_user)
    end

    if @user.update(user_params)
      flash[:notice] = "Profile Updated"
      redirect_to edit_resume_path(@resume)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :phone, :email, :first_name, :last_name, :address, :city, :state, :zip_code)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def set_resume
    @resume = Resume.find_by(user_id: session[:user_id])
  end
end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <fieldset>
    <legend><%= @user.new_record? ? "Register" : "Update Profile" %></legend>
    <div class="row">
      <div class="small-6 columns">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="small-6 columns">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>
      <div class="small-6 columns">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="small-6 columns">
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>
    </div>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <div class="row">
      <div class="medium-4 columns">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class="medium-4 columns">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>
      <div class="medium-4 columns">
        <%= f.label :zip_code %>
        <%= f.text_field :zip_code %>
      </div>
    </div>
    <%= f.submit( @user.new_record? ? "Register" : "Update Profile", class: 'button small radius' ) %>
  </fieldset>
<% end %>

app/views/users/_register_form.html.erb
<%= render 'shared/errors', obj: @user %>


<%= form_for @user do |f| %>
  <fieldset>
    <legend>Register</legend>
    <div class="row">
      <div class="small-6 columns">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="small-6 columns">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
    </div>

    <div class="row">
      <div class="small-6 columns">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>
      <div class="small-6 columns">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>
    </div>
    <%= f.submit "Register", class: 'button small radius' %>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="medium-2 columns"><%= render @user.gravatar, res_obj: @resume %></div>
  <div class="medium-10 columns"><h1><%= "#{@user.first_name} #{@user.last_name}" %></h1></div>
</div>
<hr />
<%= link_to 'Edit Gravatar Settings', edit_user_gravatar_path(@user, @user.gravatar), class: 'button small radius' %>
<%= render 'form' %>

<%= link_to "<i class=\"fi-arrow-left\"></i> Back".html_safe, edit_resume_path(@resume), title: "Back to Dashboard" %>

app/views/users/new.html.erb
<%= render 'shared/title', title: "Register" %>
<%= render 'register_form' %>

<%= link_to "<i class=\"fi-arrow-left\"></i> Back".html_safe, root_path, title: "Back to Resumes" %>