config/routes.rb
Rails.application.routes.draw do

  root 'resumes#index'
  resources :resumes, except: [:new, :update] do
    resources :objectives, only: [:create, :update, :edit, :show]
    resources :skills, except: [:index, :show]
    resources :schools, except: [:index, :show]
    resources :experiences, except: [:index, :show] do
      resources :projects, except: [:index, :show]
    end
    resources :hobbies, except: [:index, :show]
    resources :references, except: [:index, :show]
    resources :customs, except: [:index, :show]
    resources :snippets, except: [:index, :show]
  end

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :edit, :update] do
    resources :gravatars, only: [:create, :edit, :update]
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  include Sluggable
  sluggable_column :name

  belongs_to :experiences
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :set_experience
  before_action :set_resume
  before_action :require_user, except: [:index, :show]
  before_action :require_resume, except: [:index, :show]

  def create
    @project = Project.new(project_params)
    @project.experience_id = @job.id

    if @project.save
      flash[:notice] = "Project Saved"
      redirect_to edit_resume_experience_path(@resume, @job)
    else
      render 'experiences/edit'
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project Updated"
      redirect_to edit_resume_experience_path(@resume, @job)
    else
      render 'experiences/edit'
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project Deleted"
    redirect_to edit_resume_experience_path(@resume, @job)
  end

  private

  def set_project
    @project = Project.find_by(slug: params[:id])
  end

  def set_experience
    @job = Experience.find_by(slug: params[:experience_id])
  end

  def set_resume
    @resume = Resume.find_by(slug: params[:resume_id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :url)
  end

end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

<%= form_for [@resume, @job, @project] do |f| %>
  <fieldset>
    <legend><%= create_or_update(@project) %></legend>
    <p>Use this form to add a name and description for a project that you worked on related to this particular job.</p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
    <%= f.submit create_or_update(@project), class: 'button small radius' %>
  </fieldset>
<% end %>

app/views/projects/_project.html.erb
<p>
  <%= link_to "<i class=\"fi-pencil right\"></i>".html_safe, edit_resume_experience_project_path(@resume, @job, project), title: 'Edit', remote: true %>
  <%= link_to "<i class=\"fi-trash right\"></i>".html_safe, [@resume, @job, project], method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete', class: 'warning' %>
  <strong><%= project.name %></strong>  - <%= project.description %>
</p>
<hr />

app/views/projects/edit.html.erb
<%= render 'shared/title', title: "Edit Project" %>
<div class="row">
  <div class="medium-4 columns">
    <%= render 'form' %>
    <% unless @project.new_record? %>
      <%= link_to "<i class=\"fi-arrow-left\"></i> Back".html_safe, edit_resume_experience_path(@resume, @job), title: "Back to Experience" %>
    <% end %>
  </div>
</div>

app/views/projects/edit.js.erb
$("#modal").html('<a class="close-reveal-modal">&#215;</a>');
$("<%= escape_javascript(render 'projects/form') %>").prependTo('#modal');
$("<%= escape_javascript(render 'shared/title', title: "Edit Project") %>").prependTo('#modal');
$('#modal').foundation('reveal', 'open');