config/routes.rb
Rails.application.routes.draw do

  root 'resumes#index'
  resources :resumes, except: [:new, :update] do
    resources :objectives, only: [:create, :update, :edit, :show]
    resources :skills, except: [:index, :show]
    resources :schools, except: [:index, :show]
    resources :experiences, except: [:index, :show] do
      resources :projects, except: [:index, :show]
    end
    resources :hobbies, except: [:index, :show]
    resources :references, except: [:index, :show]
    resources :customs, except: [:index, :show]
    resources :snippets, except: [:index, :show]
  end

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:create, :edit, :update] do
    resources :gravatars, only: [:create, :edit, :update]
  end

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  include Sluggable
  user_column :last_name

  has_many :schools
  has_many :hobbies
  has_many :experiences
  has_many :skills
  has_many :references
  has_many :customs
  has_many :snippets
  has_one :objective
  belongs_to :user
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
    before_action :set_resume, only: [:show, :edit]
    before_action :require_user, except: [:index, :show]
    before_action :require_resume, except: [:index, :show]

  def index
    @resumes = Resume.order(created_at: :desc)
    @new_resume = Resume.new
  end

  def show
    @objective = @resume.objective
    @skills = @resume.skills
    @schools = @resume.schools
    @jobs = @resume.experiences
    @hobbies = @resume.hobbies
    @references = @resume.references
    @customs = @resume.customs
    @snippets = @resume.snippets
  end

  def edit
    @objective = Objective.new
    @skills = @resume.skills
    @schools = @resume.schools
    @jobs = @resume.experiences
    @hobbies = @resume.hobbies
    @references = @resume.references
    @customs = @resume.customs
    @snippets = @resume.snippets
  end

  private

  def set_resume
    @resume = Resume.find_by(slug: params[:id])
  end
end

app/views/resumes/_form.html.erb
<%= form_for @new_resume do |f| %>
  <%= f.submit "Create", class: 'button' %>
<% end %>

app/views/resumes/_resume.html.erb
<div class="row">
  <div class="small-2 columns">
    <%= render resume.user.gravatar, res_obj: resume %>
  </div>
  <div class="small-10 columns">
    <blockquote><h3><%= link_to "#{resume.user.first_name} #{resume.user.last_name}", resume_path(resume) %></h3>
      <% if resume.objective %>
        <p><strong> Objective</strong> - <%= resume.objective.description %></p>
      <% end %></blockquote>
  </div>
</div>

app/views/resumes/edit.html.erb
<%= render 'shared/title', title: "Build your Resume" %>
<%= render 'layouts/messages' %>
<div class="row">
  <div class="medium-6 columns">
    <h3 class="subheader">Welcome, <%= current_user.first_name %></h3>
    <hr />
    <p>Building your resume is easy.  Use the panels below to add items to your resume.  Use the text area to enter an objective.  An objective is a great way to describe your career and life goals.</p>
    <%= link_to "<i class=\"fi-pencil\"></i> Edit Profile".html_safe, edit_user_path(current_user), class: 'small button radius' %>
    <%= link_to "<i class=\"fi-eye\"></i> View Resume".html_safe, resume_path(@resume), class: 'small button radius' %>
  </div>
  <div class="medium-6 columns">
    <h3>Objective</h3>
    <hr />
    <% if @resume.objective %>
      <p><%= @resume.objective.description %></p>
      <%= link_to "<i class=\"fi-pencil\"></i> Edit Objective".html_safe, edit_resume_objective_path(@resume,@resume.objective), class: 'button small radius', remote: true %>
    <% else %>
      <%= render 'objectives/form' %>
    <% end %>

  </div>
</div>

<div class="row" data-equalizer>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @skills, title: "Skills" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Skill".html_safe, new_resume_skill_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @schools, title: "Education" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add School".html_safe, new_resume_school_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @jobs, title: "Work Experience" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Job".html_safe, new_resume_experience_path(@resume), class: 'button small radius' %>
    </div>
  </div>
</div>
<div class="row" data-equalizer>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @hobbies, title: "Hobbies" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Hobby".html_safe, new_resume_hobby_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @references, title: "References" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Reference".html_safe, new_resume_reference_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
  <div class="medium-4 columns">
    <div class="panel" data-equalizer-watch>
      <%= render 'shared/resume_panel', objs: @customs, title: "Custom" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Custom".html_safe, new_resume_custom_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
</div>
<div class="row">
  <div class="medium-4 columns">
    <div class="panel">
      <%= render 'shared/resume_panel', objs: @snippets, title: "Code Snippets" %>
      <%= link_to "<i class=\"fi-plus\"></i>Add Snippet".html_safe, new_resume_snippet_path(@resume), class: 'button small radius', remote: true %>
    </div>
  </div>
</div>

app/views/resumes/index.html.erb
<%= render 'shared/title', title: "Resume Builder" %>
<%= render 'layouts/messages' %>
<div class="row">
  <div class="medium-8 columns">
    <p>Welcome to Rails Resume, an easy apllication that you can use to build a professional single web page resume.  Rails resume is built using the Ruby on Rails framework.  Take a look at some of the recent resumes that have been published.</p>
    <% if @resumes.any? %>
      <h3>Recent Resumes</h3>
      <%= render @resumes[0..4] %>
    <% end %>
  </div>
  <% unless logged_in? %>
    <div class="medium-4 columns panel">
      <h3>Create a Resume</h3>
      <%= link_to "Sign Up", register_path, class: 'small button radius' %>
      <p>Already Signed Up? - <%= link_to 'Login', login_path %></p>
    </div>
  <% end %>
</div>

app/views/resumes/show.html.erb
<div class="row">
  <div class="medium-2 columns">
      <%= render @resume.user.gravatar, res_obj: @resume %>
  </div>
  <div class="medium-10 columns">
      <h1><%= "#{@resume.user.first_name} #{@resume.user.last_name}" %></h1>
      <ul class="no-bullet">
      <li><%= @resume.user.phone %></li>
      <li><%= @resume.user.email %></li>
      <li><%= @resume.user.address %></li>
      <li><%= @resume.user.city + ", " + @resume.user.state + " " + @resume.user.zip_code %></li>
      </ul>
  </div>
</div>
<hr />

<div class="row">
  <div id="sections" class="medium-8 columns medium-centered">
    <% if @resume.objective %>
        <section id="objective" class="current">
          <h3>Objective</h3>
          <hr />
          <p><%= @resume.objective.description %></p>
        </section>
    <% end %>

    <% if @skills.any? %>
        <section id="skills">
          <h3>Skills</h3>
          <hr />
          <% @skills.each do |skill| %>
            <p><strong><%= skill.title %> - </strong><%= skill.description %></p>
          <% end %>
        </section>
    <% end %>
    
    <% if @schools.any? %>
        <section id="schools">
          <h3>Education</h3>
          <hr />
          <% @schools.each do |school| %>
            <h3><%= school.name %> <small>Graduated in <%= school.year_graduated %></small></h3>
            <h5 class="subheader"><%= school.degree %></h5>
          <% end %>
        </section>
    <% end %>
    
    <% if @jobs.any? %>
        <section id="jobs">
          <h3>Work Experience</h3>
          <hr />
          <% @jobs.each do |job| %>
            <h3><%= job.job_title %> <small><%= job.start_date %> - <%= job.end_date %></small></h3>
            <h5 class="subheader"><%= job.company %>, <%= job.city %>, <%= job.state %> <%= job.phone %></h5>
            <% if job.url %>
              <h5><%= link_to job.url, fix_url(job.url) %></h5>
            <% end %>
            <p><%= job.responsibilities %></p>
            <% if job.projects.any? %>
            <h5>Projects</h5>
            <ul>
            <% job.projects.each do |project| %>
              <li>
                <strong><%= project.name %></strong> - 
                <% if project.url %>
                  <%= link_to project.url, fix_url(project.url) %> - 
                <% end %>
                <%= project.description %>
              </li>
            <% end %>
            </ul>
            <% end %>
          <% end %>
        </section>
    <% end %>

    <% if @hobbies.any? %>
        <section id="hobbies">
          <h3>Hobbies</h3>
          <hr />
          <% @hobbies.each do |hobby| %>
            <p><strong><%= hobby.title %></strong> - <%= hobby.description %></p>
          <% end %>
        </section>
    <% end %>

    <% if @references.any? %>
        <section id="references">
          <h3>References</h3>
          <hr />
          <% @references.each do |reference| %>
            <p>
            <strong><%= reference.name %></strong> - <%= reference.relationship %><br/>
            <ul class="no-bullet">
              <li><%= reference.company %></li>
              <li><%= reference.phone %></li>
              <li><%= reference.email %></li>
            </ul>
            </p>
          <% end %>
      
        </section>
    <% end %>
    
    <% @customs.each do |custom| %>
      <section id="custom-<%= custom.id %>">
        <h3><%= custom.title %></h3>
        <hr />
        <p>
          <%= custom.description %>
        </p>

      </section>
    <% end %>

    <% @snippets.each do |snippet| %>
      <section id="snippet-<%= snippet.id %>">
        <h3><%= snippet.title %></h3>
        <hr />
        <p><%= snippet.description %></p>
        <pre><code <%= snippet_lang(snippet).html_safe %>><%= snippet.code %></code></pre>
      </section>
    <% end %>
  </div>
</div>